HDRS=	fifo.h \
	overlay_buffer.h \
	overlay_address.h \
	overlay_packet.h \
	overlay_interface.h \
	section.h \
	trigger.h \
	commandline.h \
	limit.h \
	rhizome_types.h \
	rhizome.h \
	sync_keys.h \
	httpd.h \
	instance.h \
	meshms.h \
	meshmb.h \
	message_ply.h \
	nibble_tree.h \
	serval_types.h \
	serval.h \
	server.h \
	route_link.h \
	keyring.h \
	socket.h \
	cli.h \
	str.h \
	numeric_str.h \
	base64.h \
	uri.h \
	rotbuf.h \
	mem.h \
	os.h \
	serval_uuid.h \
	sighandlers.h \
	strbuf.h \
	strbuf_helpers.h \
	conf.h \
	conf_schema.h \
	crypto.h \
	dataformats.h \
	log.h \
	log_output.h \
	debug.h \
	net.h \
	fdqueue.h \
	http_server.h \
	xprintf.h \
	lang.h \
	constants.h \
	monitor-client.h \
	mdp_client.h \
	msp_client.h \
	msp_common.h \
	msp_server.h \
	radio_link.h \
	$(SQLITE3_AMALGAMATION)/sqlite3.h
