HDRS=	fifo.h \
	Makefile \
	overlay_buffer.h \
	overlay_address.h \
	overlay_packet.h \
	rhizome.h \
	serval.h \
	keyring.h \
	socket.h \
	cli.h \
	str.h \
	rotbuf.h \
	mem.h \
	os.h \
	uuid.h \
	strbuf.h \
	strbuf_helpers.h \
	sha2.h \
	network_coding.h \
	conf.h \
	conf_schema.h \
	crypto.h \
	dataformats.h \
	log.h \
	net.h \
	fdqueue.h \
	http_server.h \
	xprintf.h \
	constants.h \
	monitor-client.h \
	mdp_client.h \
	radio_link.h \
	sqlite-amalgamation-3070900/sqlite3.h
