/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_servalproject_servald_mdp_MeshSocket */

#ifndef _Included_org_servalproject_servald_mdp_MeshSocket
#define _Included_org_servalproject_servald_mdp_MeshSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket_init
  (JNIEnv *, jclass);

/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    _create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket__1create
  (JNIEnv *, jobject);

/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    _bind
 * Signature: (ILorg/servalproject/servald/SubscriberId;)V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket__1bind
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    _send
 * Signature: (Lorg/servalproject/servald/mdp/MeshPacket;)V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket__1send
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    _receive
 * Signature: (Lorg/servalproject/servald/mdp/MeshPacket;)V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket__1receive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_servalproject_servald_mdp_MeshSocket
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_servalproject_servald_mdp_MeshSocket__1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
