#!/bin/sh

toolchain=$HOME/OpenWrt-SDK-atheros-for-Linux-i686/staging_dir/toolchain-mips_gcc4.1.2

$toolchain/bin/mips-linux-gcc -DHAVE_SYS_MMAN_H -DHAVE_STDINT_H -DHAVE_SYS_STAT_H -DHAVE_POLL_H -DHAVE_ARPA_INET_H -DHAVE_BZERO -o dna.meshpotato `ls -1 *.c | egrep -v "asterisk_app.c|serval.c"`
$toolchain/bin/mips-linux-strip dna.meshpotato
