SERVAL_SOURCES = $(SERVAL_BASE)audiodevices.c \
	$(SERVAL_BASE)audio_reflector.c \
	$(SERVAL_BASE)cli.c \
	$(SERVAL_BASE)codecs.c \
	$(SERVAL_BASE)commandline.c \
	$(SERVAL_BASE)conf.c \
	$(SERVAL_BASE)crypto.c \
	$(SERVAL_BASE)dataformats.c \
	$(SERVAL_BASE)directory_client.c \
	$(SERVAL_BASE)dna_helper.c \
	$(SERVAL_BASE)encode.c \
	$(SERVAL_BASE)fdqueue.c \
	$(SERVAL_BASE)fifo.c \
	$(SERVAL_BASE)keyring.c \
	$(SERVAL_BASE)log.c \
	$(SERVAL_BASE)lsif.c \
	$(SERVAL_BASE)main.c \
	$(SERVAL_BASE)mdp_client.c \
	$(SERVAL_BASE)mdp_jni.c \
	$(SERVAL_BASE)mkdir.c \
	$(SERVAL_BASE)monitor.c \
	$(SERVAL_BASE)monitor-client.c \
	$(SERVAL_BASE)monitor-cli.c \
	$(SERVAL_BASE)net.c \
	$(SERVAL_BASE)overlay.c \
	$(SERVAL_BASE)overlay_advertise.c \
	$(SERVAL_BASE)overlay_address.c \
	$(SERVAL_BASE)overlay_buffer.c \
	$(SERVAL_BASE)overlay_interface.c \
	$(SERVAL_BASE)overlay_mdp.c \
	$(SERVAL_BASE)overlay_olsr.c \
	$(SERVAL_BASE)overlay_packetformats.c \
	$(SERVAL_BASE)overlay_payload.c \
	$(SERVAL_BASE)overlay_route.c \
	$(SERVAL_BASE)packetformats.c \
	$(SERVAL_BASE)performance_timing.c \
	$(SERVAL_BASE)randombytes.c \
	$(SERVAL_BASE)rhizome.c \
	$(SERVAL_BASE)rhizome_bundle.c \
	$(SERVAL_BASE)rhizome_crypto.c \
	$(SERVAL_BASE)rhizome_database.c \
	$(SERVAL_BASE)rhizome_direct.c \
	$(SERVAL_BASE)rhizome_direct_http.c \
	$(SERVAL_BASE)rhizome_fetch.c \
	$(SERVAL_BASE)rhizome_http.c \
	$(SERVAL_BASE)rhizome_packetformats.c \
	$(SERVAL_BASE)serval_packetvisualise.c \
	$(SERVAL_BASE)server.c \
	$(SERVAL_BASE)sha2.c \
	$(SERVAL_BASE)sighandlers.c \
	$(SERVAL_BASE)sqlite-amalgamation-3070900/sqlite3.c \
	$(SERVAL_BASE)srandomdev.c \
	$(SERVAL_BASE)str.c \
	$(SERVAL_BASE)strbuf.c \
	$(SERVAL_BASE)strbuf_helpers.c \
	$(SERVAL_BASE)strlcpy.c \
	$(SERVAL_BASE)vomp.c \
	$(SERVAL_BASE)vomp_console.c \
	$(SERVAL_BASE)xprintf.c
