SERVAL_SOURCES = \
	$(SERVAL_BASE)cli.c \
	$(SERVAL_BASE)commandline.c \
	$(SERVAL_BASE)conf.c \
	$(SERVAL_BASE)conf_om.c \
	$(SERVAL_BASE)conf_parse.c \
	$(SERVAL_BASE)conf_schema.c \
	$(SERVAL_BASE)crc32.c \
	$(SERVAL_BASE)crypto.c \
	$(SERVAL_BASE)dataformats.c \
	$(SERVAL_BASE)directory_client.c \
	$(SERVAL_BASE)dna_helper.c \
	$(SERVAL_BASE)encode.c \
	$(SERVAL_BASE)fdqueue.c \
	$(SERVAL_BASE)fifo.c \
	$(SERVAL_BASE)golay.c \
	$(SERVAL_BASE)http_server.c \
	$(SERVAL_BASE)keyring.c \
	$(SERVAL_BASE)log.c \
	$(SERVAL_BASE)lsif.c \
	$(SERVAL_BASE)main.c \
	$(SERVAL_BASE)radio_link.c \
	$(SERVAL_BASE)meshms.c \
	$(SERVAL_BASE)mdp_client.c \
	$(SERVAL_BASE)os.c \
	$(SERVAL_BASE)mem.c \
	$(SERVAL_BASE)instance.c \
	$(SERVAL_BASE)socket.c \
	$(SERVAL_BASE)monitor.c \
	$(SERVAL_BASE)monitor-client.c \
	$(SERVAL_BASE)monitor-cli.c \
	$(SERVAL_BASE)net.c \
	$(SERVAL_BASE)nonce.c \
	$(SERVAL_BASE)overlay.c \
	$(SERVAL_BASE)overlay_address.c \
	$(SERVAL_BASE)overlay_buffer.c \
	$(SERVAL_BASE)overlay_interface.c \
	$(SERVAL_BASE)overlay_link.c \
	$(SERVAL_BASE)overlay_packetradio.c \
	$(SERVAL_BASE)overlay_queue.c \
	$(SERVAL_BASE)overlay_mdp.c \
	$(SERVAL_BASE)overlay_mdp_services.c \
	$(SERVAL_BASE)overlay_olsr.c \
	$(SERVAL_BASE)overlay_packetformats.c \
	$(SERVAL_BASE)overlay_payload.c \
	$(SERVAL_BASE)performance_timing.c \
	$(SERVAL_BASE)randombytes.c \
	$(SERVAL_BASE)route_link.c \
	$(SERVAL_BASE)rhizome.c \
	$(SERVAL_BASE)rhizome_bundle.c \
	$(SERVAL_BASE)rhizome_crypto.c \
	$(SERVAL_BASE)rhizome_database.c \
	$(SERVAL_BASE)rhizome_direct.c \
	$(SERVAL_BASE)rhizome_direct_http.c \
	$(SERVAL_BASE)rhizome_fetch.c \
	$(SERVAL_BASE)rhizome_http.c \
	$(SERVAL_BASE)rhizome_packetformats.c \
	$(SERVAL_BASE)rhizome_store.c \
	$(SERVAL_BASE)rhizome_sync.c \
	$(SERVAL_BASE)rotbuf.c \
	$(SERVAL_BASE)serval_packetvisualise.c \
	$(SERVAL_BASE)server.c \
	$(SERVAL_BASE)sha2.c \
	$(SERVAL_BASE)sighandlers.c \
	$(SERVAL_BASE)slip.c \
	$(SERVAL_BASE)sqlite-amalgamation-3070900/sqlite3.c \
	$(SERVAL_BASE)srandomdev.c \
	$(SERVAL_BASE)str.c \
	$(SERVAL_BASE)strbuf.c \
	$(SERVAL_BASE)strbuf_helpers.c \
	$(SERVAL_BASE)strlcpy.c \
	$(SERVAL_BASE)uuid.c \
	$(SERVAL_BASE)vomp.c \
	$(SERVAL_BASE)vomp_console.c \
	$(SERVAL_BASE)xprintf.c \
        $(SERVAL_BASE)fec-3.0.1/ccsds_tables.c \
	$(SERVAL_BASE)fec-3.0.1/decode_rs_8.c \
	$(SERVAL_BASE)fec-3.0.1/encode_rs_8.c \
	$(SERVAL_BASE)fec-3.0.1/init_rs_char.c \
	$(SERVAL_BASE)context1.c 
