#!/bin/bash

# Aggregation of all tests except high-load stress tests.
#
# Copyright 2012 Serval Project, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

source "${0%/*}/../testframework.sh"
source "${0%/*}/../testconfig.sh"

includeTests logging
includeTests config
includeTests keyring
includeTests server
includeTests routing
includeTests mdp
includeTests msp
includeTests dnahelper
includeTests dnaprotocol
includeTests rhizomeops
includeTests rhizomeprotocol
includeTests rhizomehttp
includeTests meshms
includeTests directory_service
includeTests vomp
if type -p "$JAVAC" >/dev/null; then
   includeTests jni
   includeTests meshmsjava
fi

runTests "$@"
