#!/bin/bash

# Tests for Serval DNA JNI entry points.
#
# Copyright 2012 Paul Gardner-Stephen
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

source "${0%/*}/../testframework.sh"
source "${0%/*}/../testdefs.sh"
source "${0%/*}/../testconfig.sh"

setup() {
   setup_dna
   compile_java_classes
}

compile_java_classes() {
   local batphone_source=$(abspath "$here/../..")
   assert [ "$JAVAC" ]
   mkdir classes
   assert $JAVAC -d classes "$batphone_source"/src/org/servalproject/servald/*.java
   assert [ -r classes/org/servalproject/servald/ServalD.class ]
}

doc_Echo="Serval echo command works via JNI"
test_Echo() {
   execute $dna echo "Hello," "world!"
   assertStdoutIs -e 'Hello,\nworld!\n'
}

runTests "$@"

